"""Many to Many Followers.

Revision ID: 170f218e02a7
Revises: 1564f1d4b8f
Create Date: 2014-03-03 21:01:19.382305

"""

# revision identifiers, used by Alembic.
revision = '170f218e02a7'
down_revision = '1564f1d4b8f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    ### end Alembic commands ###
