"""create_user

Revision ID: 3384e8385b9e
Revises: 4b4f454f5e86
Create Date: 2014-02-27 22:46:03.792034

"""

# revision identifiers, used by Alembic.
revision = '3384e8385b9e'
down_revision = '4b4f454f5e86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_nickname', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
