"""empty message

Revision ID: 4b4f454f5e86
Revises: None
Create Date: 2014-02-27 22:23:56.692038

"""

# revision identifiers, used by Alembic.
revision = '4b4f454f5e86'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
